import type { Metadata } from "next";
import "./globals.css";
import { Plus_Jakarta_Sans, DM_Serif_Display } from 'next/font/google'

const jakarta = Plus_Jakarta_Sans({ 
  subsets: ['latin'], 
  variable: '--font-jakarta',
  display: 'swap',
})

const dmSerif = DM_Serif_Display({ 
  weight: ['400'], 
  subsets: ['latin'], 
  variable: '--font-dm-serif',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${jakarta.variable} ${dmSerif.variable}`}>
      <body
        className="font-sans antialiased bg-stone-50"
      >
        {children}
      </body>
    </html>
  );
}
